// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7rIuQHiSBjzkWd1NGu0j8UDSP-8zCog0',
    appId: '1:886280369666:web:45ac74645a4cacbd1b591b',
    messagingSenderId: '886280369666',
    projectId: 'fir-flutter-codelab-e43c9',
    authDomain: 'fir-flutter-codelab-e43c9.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-e43c9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSkltzP0JaLfdJQhRrOFsWonHoIxUario',
    appId: '1:886280369666:android:0e32f6117e11c2e71b591b',
    messagingSenderId: '886280369666',
    projectId: 'fir-flutter-codelab-e43c9',
    storageBucket: 'fir-flutter-codelab-e43c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYyr0DFfSssenOTxucRMVGc16wV9JWtPo',
    appId: '1:886280369666:ios:5494dbf06db632c81b591b',
    messagingSenderId: '886280369666',
    projectId: 'fir-flutter-codelab-e43c9',
    storageBucket: 'fir-flutter-codelab-e43c9.appspot.com',
    iosClientId: '886280369666-dgvlti9kd9402utkpqhid56ervm2a6no.apps.googleusercontent.com',
    iosBundleId: 'com.example.start',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYyr0DFfSssenOTxucRMVGc16wV9JWtPo',
    appId: '1:886280369666:ios:5494dbf06db632c81b591b',
    messagingSenderId: '886280369666',
    projectId: 'fir-flutter-codelab-e43c9',
    storageBucket: 'fir-flutter-codelab-e43c9.appspot.com',
    iosClientId: '886280369666-dgvlti9kd9402utkpqhid56ervm2a6no.apps.googleusercontent.com',
    iosBundleId: 'com.example.start',
  );
}
